# -*- coding: utf-8 -*-
"""PMSM_Loss_Modelling_Redesigned_v2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PWKmdZzJmo_zW75hdwJGbjSdQjs3QeF8

# PMSM Loss Modelling — Redesigned Colab Notebook

## Goal

Compare multiple ways to estimate PMSM loss from operating conditions:

- material-derived physics,
- compact reduced-order regression,
- polynomial regression,
- gradient boosting,
- pure MLP,
- physics + residual MLP,
- physics-guided neural network.

The notebook also adds:

- signal-alignment diagnostics,
- explicit handling of negative instantaneous measured loss,
- leave-one-cycle-out testing,
- operating-region extrapolation,
- operating-map-aware low-data studies,
- cycle-integrated energy error,
- temperature sensitivity of copper loss.

The main research question is:

**When does physics actually help data-driven PMSM loss estimation?**

## 
"""

# 0. Imports
import os, re, glob, zipfile, urllib.request, warnings
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

try:
    from IPython.display import display
except ImportError:
    def display(obj=None, *args, **kwargs):
        if obj is not None:
            print(obj)
        for arg in args:
            print(arg)

from scipy.optimize import curve_fit
from scipy.signal import correlate, correlation_lags

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, PolynomialFeatures
from sklearn.linear_model import Ridge
from sklearn.ensemble import HistGradientBoostingRegressor
from sklearn.neural_network import MLPRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.model_selection import train_test_split
from sklearn.neighbors import NearestNeighbors

import torch
import torch.nn as nn

SEED = 42
np.random.seed(SEED)
torch.manual_seed(SEED)
warnings.filterwarnings("ignore")
pd.set_option("display.max_columns", 100)

# 1. Configuration
DATA_DIR = "creator_case"
ROOT = f"{DATA_DIR}/PM_synchronous_motor/PM_synchronous_motor"
LOCAL_DATA_ROOT = r"C:\Users\irinj\OneDrive\Documents\Projects\PMSM_LossModelling\PM_synchronous_motor\PM_synchronous_motor"
if not os.path.exists(ROOT) and os.path.exists(LOCAL_DATA_ROOT):
    ROOT = LOCAL_DATA_ROOT

DOWNLOAD_DATA = True

# Alignment: first diagnose; only enable after inspecting results.
DIAGNOSE_ALIGNMENT = True
APPLY_ALIGNMENT_SHIFT = False
MAX_ALIGNMENT_LAG_S = 2.0

# Target handling
TARGET_POLICY = "exclude"   # "exclude" or "keep"
REL_ERR_MIN_LOSS_W = 0.05

# Steel model
B_SAT_LIMIT_T = 1.3

# Physics-guided NN
PHYSICS_LAMBDAS = [0.0, 0.01, 0.05, 0.1, 0.25, 0.5, 1.0, 2.0]

# Low-data study
LOW_DATA_SIZES = [20, 50, 100, 250, 500, 1000, 2500, 5000]
LOW_DATA_REPEATS = 5
N_SPEED_BINS = 10
N_TORQUE_BINS = 10

# 2. Download and extract dataset
if DOWNLOAD_DATA and not os.path.exists(ROOT):
    base = "https://repository.tugraz.at/records/sns1d-77m43/files/"
    files = [
        "PM_synchronous_motor.zip",
        "README.md",
        "CREATOR_Machine_Data_2024-11-04.pdf"
    ]
    os.makedirs(DATA_DIR, exist_ok=True)

    for fname in files:
        target = f"{DATA_DIR}/{fname}"
        if not os.path.exists(target):
            print("Downloading", fname)
            urllib.request.urlretrieve(base + fname + "?download=1", target)

    extract_dir = f"{DATA_DIR}/PM_synchronous_motor"
    if not os.path.exists(ROOT):
        with zipfile.ZipFile(f"{DATA_DIR}/PM_synchronous_motor.zip", "r") as z:
            z.extractall(extract_dir)

print("ROOT:", ROOT)
print("Exists:", os.path.exists(ROOT))

"""## Utility functions


"""

# 3. Utility functions
def get_val(df, name):
    row = df.loc[df["Parameter"].astype(str).str.contains(name, case=False, na=False)]
    if len(row) == 0:
        raise KeyError(f"Could not find parameter containing: {name}")
    return row["Value"].values[0]

def load_cycle_csv(path, names):
    raw = pd.read_csv(path, header=None)
    raw = raw.iloc[:, :len(names)].copy()
    raw.columns = names
    for c in names:
        raw[c] = pd.to_numeric(raw[c], errors="coerce")
    return raw.dropna().reset_index(drop=True)

def discover_cycles(ts_base):
    out = []
    for vehicle in sorted(os.listdir(ts_base)):
        d = os.path.join(ts_base, vehicle)
        if not os.path.isdir(d):
            continue
        for path in glob.glob(os.path.join(d, "*_speed_rpm.csv")):
            cycle = os.path.basename(path).replace("_speed_rpm.csv", "")
            torque_path = os.path.join(d, f"{cycle}_torque_nm.csv")
            if os.path.exists(torque_path):
                out.append((vehicle, cycle))
    return out

def cycle_energy_wh(time_s, power_w):
    t = np.asarray(time_s, dtype=float)
    p = np.asarray(power_w, dtype=float)
    if len(t) < 2:
        return np.nan
    trapz_fn = getattr(np, "trapz", getattr(np, "trapezoid", None))
    return trapz_fn(p, t) / 3600.0

def metrics_dict(y_true, y_pred, time_s=None, rel_floor=REL_ERR_MIN_LOSS_W):
    y_true = np.asarray(y_true, dtype=float)
    y_pred = np.asarray(y_pred, dtype=float)
    abs_err = np.abs(y_pred - y_true)
    mask = np.abs(y_true) >= rel_floor

    out = {
        "MAE_W": mean_absolute_error(y_true, y_pred),
        "RMSE_W": mean_squared_error(y_true, y_pred) ** 0.5,
        "R2": r2_score(y_true, y_pred),
        "MedianAbsErr_W": np.median(abs_err),
        "MedianRelErr_pct": (
            np.median(abs_err[mask] / np.abs(y_true[mask])) * 100
            if mask.any() else np.nan
        ),
        "MeanRelErr_pct": (
            np.mean(abs_err[mask] / np.abs(y_true[mask])) * 100
            if mask.any() else np.nan
        )
    }

    if time_s is not None:
        e_true = cycle_energy_wh(time_s, y_true)
        e_pred = cycle_energy_wh(time_s, y_pred)
        out["TrueEnergy_Wh"] = e_true
        out["PredEnergy_Wh"] = e_pred
        out["CycleEnergyErr_pct"] = (
            abs(e_pred - e_true) / abs(e_true) * 100
            if np.isfinite(e_true) and abs(e_true) > 1e-12 else np.nan
        )
    return out

# 4. Load motor/material parameter tables
elec_df = pd.read_csv(
    f"{ROOT}/Design_parameters/Electrical_parameters/Electrical_properties_of_PMSM.csv"
).dropna(how="all").reset_index(drop=True)

eq_df = pd.read_csv(
    f"{ROOT}/Measurement_results/Equivalent_circuit_parameters/Equivalent_circuit_parameters_PMSM.csv"
).dropna(how="all").reset_index(drop=True)

geom_df = pd.read_csv(
    f"{ROOT}/Design_parameters/Motor_geometry/Geometry_parameters_PMSM.csv"
).dropna(how="all").reset_index(drop=True)

steel_props_df = pd.read_csv(
    f"{ROOT}/Design_parameters/Material_properties/Electrical_steel/Steel_properties.csv"
).dropna(how="all").reset_index(drop=True)

winding_df = pd.read_csv(
    f"{ROOT}/Design_parameters/Winding_scheme/Winding_properties_of_PMSM.csv"
).dropna(how="all").reset_index(drop=True)

E0 = float(get_val(eq_df, "back emf"))
lam_pm = float(get_val(eq_df, "flux linkage"))

n_ref_rpm = 2000.0
omega_ref = n_ref_rpm * 2*np.pi/60
pole_pairs_est = E0 / (omega_ref * lam_pm)
pole_pairs = int(round(pole_pairs_est))

f_nom = float(get_val(elec_df, "Nominal frequency"))
implied_rpm = f_nom * 60 / pole_pairs

print(f"pole-pair estimate = {pole_pairs_est:.3f} -> {pole_pairs}")
print(f"nominal-frequency cross-check speed = {implied_rpm:.1f} rpm")

# 5. Approximate stator steel mass
poles = 2 * pole_pairs
phases = 3

try:
    q = float(get_val(winding_df, "slots per pole per phase"))
except Exception:
    q = 0.5

n_slots = q * poles * phases

D_out = float(get_val(geom_df, "Stator outer diameter"))
D_in = float(get_val(geom_df, "Stator inner diameter"))
slot_h = float(get_val(geom_df, "Slot height"))
slot_w = float(get_val(geom_df, "Slot width"))
stack_length = float(get_val(geom_df, "Motor length"))

annulus_area_mm2 = np.pi/4 * (D_out**2 - D_in**2)
slot_area_mm2 = n_slots * slot_h * slot_w
stator_area_mm2 = annulus_area_mm2 - slot_area_mm2

stator_volume_m3 = stator_area_mm2 * stack_length * 1e-9
density_kgm3 = float(get_val(steel_props_df, "Density")) * 1000
stator_mass_kg = stator_volume_m3 * density_kgm3

print(f"Derived slot count: {n_slots:g}")
print(f"Approximate stator steel mass: {stator_mass_kg:.4f} kg")

"""## Material-derived iron-loss model

Fit

\[
p_{Fe} = K_h f B^\alpha + K_e f^2 B^2
\]

using measured electrical-steel data.

To avoid a mathematically good but physically implausible nonlinear fit, estimate \(\alpha\) first from a low-frequency/moderate-\(B\) slice, then solve for \(K_h,K_e\) by least squares.
"""

# 6. Build material-loss dataset and fit two-term model
steel_data_dir = f"{ROOT}/Design_parameters/Material_properties/Electrical_steel/Data"
rows = []

for path in glob.glob(f"{steel_data_dir}/*_Hz.csv"):
    m = re.search(r"(\d+)_Hz", os.path.basename(path))
    if not m:
        continue
    freq_hz = int(m.group(1))

    df = pd.read_csv(path).rename(columns={
        "Flux density in T": "B",
        "Specific loss in W/kg": "loss_wkg"
    })
    df["B"] = pd.to_numeric(df["B"], errors="coerce")
    df["loss_wkg"] = pd.to_numeric(df["loss_wkg"], errors="coerce")
    df["freq_hz"] = freq_hz
    rows.append(df[["freq_hz", "B", "loss_wkg"]].dropna())

steel_long = pd.concat(rows, ignore_index=True).sort_values(["freq_hz", "B"])

alpha_slice = None
for f0 in sorted(steel_long["freq_hz"].unique()):
    tmp = steel_long[
        (steel_long["freq_hz"] == f0) &
        (steel_long["B"] >= 0.3) &
        (steel_long["B"] <= 1.0) &
        (steel_long["loss_wkg"] > 0)
    ]
    if len(tmp) >= 3:
        alpha_slice = tmp
        alpha_freq = f0
        break

alpha_fixed, _ = np.polyfit(
    np.log(alpha_slice["B"].values),
    np.log(alpha_slice["loss_wkg"].values),
    1
)

presat = steel_long[steel_long["B"] <= B_SAT_LIMIT_T].copy()
f_fit = presat["freq_hz"].values.astype(float)
B_fit = presat["B"].values.astype(float)
y_fit = presat["loss_wkg"].values.astype(float)

A = np.column_stack([
    f_fit * B_fit**alpha_fixed,
    f_fit**2 * B_fit**2
])

Kh, Ke = np.linalg.lstsq(A, y_fit, rcond=None)[0]
steel_pred = A @ np.array([Kh, Ke])

print(f"alpha from {alpha_freq} Hz slice = {alpha_fixed:.4f}")
print(f"Kh = {Kh:.6g}")
print(f"Ke = {Ke:.6g}")
print(metrics_dict(y_fit, steel_pred))

plt.figure(figsize=(7,5))
for f0, g in steel_long.groupby("freq_hz"):
    plt.plot(g["B"], g["loss_wkg"], marker="o", ms=3, label=f"{f0} Hz")
plt.yscale("log")
plt.xlabel("Flux density B [T]")
plt.ylabel("Specific loss [W/kg]")
plt.title("Electrical-steel loss data")
plt.grid(alpha=0.3)
plt.legend(fontsize=8, ncol=2)
plt.show()

# 7. Calibrate effective B using no-load iron-loss measurements
noload_df = pd.read_csv(
    f"{ROOT}/Measurement_results/No_load_tests/No_load_iron_losses.csv"
)

f_noload = pd.to_numeric(noload_df["Frequency"], errors="coerce").values.astype(float)
loss_noload_W = pd.to_numeric(noload_df["Iron loss"], errors="coerce").values.astype(float)

def material_iron_loss_W(f_hz, B_eff):
    specific = Kh*f_hz*(B_eff**alpha_fixed) + Ke*(f_hz**2)*(B_eff**2)
    return specific * stator_mass_kg

B_opt, _ = curve_fit(
    material_iron_loss_W,
    f_noload,
    loss_noload_W,
    p0=[0.5],
    bounds=(0.05, 2.0)
)

B_eff = float(B_opt[0])
pred_noload = material_iron_loss_W(f_noload, B_eff)

print(f"Effective B = {B_eff:.4f} T")
print(metrics_dict(loss_noload_W, pred_noload))

plt.figure(figsize=(8,4))
plt.plot(f_noload, loss_noload_W, "o-", label="Measured")
plt.plot(f_noload, pred_noload, "s--", label="Material-derived")
plt.xlabel("Electrical frequency [Hz]")
plt.ylabel("Iron loss [W]")
plt.title("No-load iron loss")
plt.grid(alpha=0.3)
plt.legend()
plt.show()

"""## Assemble drive-cycle data

Measured instantaneous loss is initially defined as:

\[
P_{loss,meas}=P_{in}-P_{out}
\]

No negative samples are removed yet.
"""

# 8. Load all complete vehicle/cycle combinations
ts_base = f"{ROOT}/Measurement_results/Drive_cycle_torque_speed_data"
power_base = f"{ROOT}/Measurement_results/Drive_cycle_measurement_results"

cycle_pairs = discover_cycles(ts_base)
cycles_raw = {}

for vehicle, cycle in cycle_pairs:
    speed_path = f"{ts_base}/{vehicle}/{cycle}_speed_rpm.csv"
    torque_path = f"{ts_base}/{vehicle}/{cycle}_torque_nm.csv"
    input_path = f"{power_base}/{vehicle}/{cycle}_input_power.csv"
    output_path = f"{power_base}/{vehicle}/{cycle}_output_power.csv"

    if not (os.path.exists(input_path) and os.path.exists(output_path)):
        continue

    speed = load_cycle_csv(speed_path, ["time_s", "speed_rpm"])
    torque = load_cycle_csv(torque_path, ["time_s", "torque_nm"])
    pin = load_cycle_csv(input_path, ["time_s", "input_power_W"])
    pout = load_cycle_csv(output_path, ["time_s", "output_power_W"])

    m = speed.merge(torque, on="time_s")
    m = m.merge(pin, on="time_s").merge(pout, on="time_s")
    m = m.sort_values("time_s").reset_index(drop=True)

    m["vehicle"] = vehicle
    m["cycle"] = cycle
    m["group"] = vehicle + "_" + cycle
    m["omega_rad_s"] = m["speed_rpm"] * 2*np.pi/60
    m["mechanical_power_from_Tw_W"] = m["torque_nm"] * m["omega_rad_s"]
    m["measured_loss_raw_W"] = m["input_power_W"] - m["output_power_W"]

    cycles_raw[m["group"].iloc[0]] = m

print("Loaded groups:")
for key, m in cycles_raw.items():
    print(key, len(m))

"""## Alignment diagnostic

Transient misalignment between measured channels can create negative instantaneous loss.

We compare measured output power with \(T\omega\), estimate the lag that maximizes correlation, and report it.  
The notebook does **not** apply that shift unless you explicitly enable `APPLY_ALIGNMENT_SHIFT`.
"""

# 9. Estimate output-power lag relative to T*omega
def estimate_lag_seconds(time_s, reference, candidate, max_lag_s=2.0):
    t = np.asarray(time_s, dtype=float)
    x = np.asarray(reference, dtype=float)
    y = np.asarray(candidate, dtype=float)

    dt = np.median(np.diff(t))
    max_lag_samples = max(1, int(round(max_lag_s / dt)))

    x = x - np.mean(x)
    y = y - np.mean(y)

    corr = correlate(x, y, mode="full")
    lags = correlation_lags(len(x), len(y), mode="full")

    mask = np.abs(lags) <= max_lag_samples
    corr2 = corr[mask]
    lags2 = lags[mask]

    i = np.argmax(corr2)
    lag_samples = int(lags2[i])

    denom = np.sqrt(np.sum(x*x) * np.sum(y*y))
    corr_norm = corr2[i] / denom if denom > 0 else np.nan

    return lag_samples*dt, corr_norm

alignment_rows = []

for key, m in cycles_raw.items():
    lag_s, corr_value = estimate_lag_seconds(
        m["time_s"],
        m["mechanical_power_from_Tw_W"],
        m["output_power_W"],
        MAX_ALIGNMENT_LAG_S
    )

    alignment_rows.append({
        "group": key,
        "estimated_lag_s": lag_s,
        "max_normalized_corr": corr_value,
        "raw_negative_loss_pct": 100*(m["measured_loss_raw_W"] < 0).mean()
    })

alignment_df = pd.DataFrame(alignment_rows)
display(alignment_df)

# 10. Optionally apply diagnosed shift
def shift_series_by_time(df, column, lag_s):
    t = df["time_s"].values.astype(float)
    y = df[column].values.astype(float)
    return np.interp(t + lag_s, t, y, left=np.nan, right=np.nan)

lag_map = dict(zip(alignment_df["group"], alignment_df["estimated_lag_s"]))
cycles = {}

for key, m0 in cycles_raw.items():
    m = m0.copy()

    if APPLY_ALIGNMENT_SHIFT:
        m["output_power_aligned_W"] = shift_series_by_time(
            m, "output_power_W", lag_map.get(key, 0.0)
        )
    else:
        m["output_power_aligned_W"] = m["output_power_W"]

    m["measured_loss_W"] = m["input_power_W"] - m["output_power_aligned_W"]
    m = m.dropna(subset=["measured_loss_W"]).reset_index(drop=True)
    cycles[key] = m

print("Alignment shift applied:", APPLY_ALIGNMENT_SHIFT)

"""## Standstill offset

Estimate it per cycle, but retain both raw and offset-adjusted values.

Negative adjusted loss is flagged explicitly rather than silently deleted.
"""

# 11. Standstill-offset diagnostic and target construction
offset_rows = []

for key, m in cycles.items():
    standstill = (
        np.isclose(m["speed_rpm"], 0.0) &
        np.isclose(m["torque_nm"], 0.0)
    )

    offset = m.loc[standstill, "measured_loss_W"].median() if standstill.any() else 0.0
    m["standby_offset_W"] = offset
    m["target_loss_W"] = m["measured_loss_W"] - offset
    m["negative_target"] = m["target_loss_W"] < 0

    offset_rows.append({
        "group": key,
        "standstill_points": int(standstill.sum()),
        "standby_offset_W": offset,
        "negative_target_pct": 100*m["negative_target"].mean()
    })

offset_df = pd.DataFrame(offset_rows)
display(offset_df)

"""## Physics model A

Use:

\[
I_q = \frac{T}{1.5p\lambda_{pm}}
\]

\[
P_{Cu}=1.5R_sI_q^2
\]

\[
P_{Fe}=m\left(K_hfB^\alpha + K_ef^2B^2\right)
\]

This is the material-derived physics baseline.

A later training-only speed-dependent correction is called **parasitic/unmodelled loss**, not automatically “friction”.
"""

# 12. Material-derived physics components
res_rows = eq_df.loc[
    eq_df["Parameter"].astype(str).str.contains("resistance", case=False, na=False)
]
Rs_ref = float(res_rows["Value"].iloc[0]) if len(res_rows) else 8.9462

def copper_resistance_at_temp(R_ref, temp_C, ref_temp_C=20.0, alpha_cu=0.00393):
    return R_ref * (1 + alpha_cu*(np.asarray(temp_C)-ref_temp_C))

def material_physics_components(df, Rs=Rs_ref, winding_temp_C=None):
    speed = df["speed_rpm"].values.astype(float)
    torque = df["torque_nm"].values.astype(float)

    Iq = torque / (1.5 * pole_pairs * lam_pm)

    if winding_temp_C is None:
        Rs_vec = np.full_like(Iq, Rs)
    else:
        Rs_vec = copper_resistance_at_temp(Rs, winding_temp_C)

    P_cu = 1.5 * Rs_vec * Iq**2

    f_e = np.abs(speed) * pole_pairs / 60
    specific_fe = Kh*f_e*(B_eff**alpha_fixed) + Ke*(f_e**2)*(B_eff**2)
    P_fe = specific_fe * stator_mass_kg

    return pd.DataFrame({
        "Iq_A": Iq,
        "P_copper_W": P_cu,
        "P_iron_W": P_fe,
        "P_physics_A_base_W": P_cu + P_fe
    }, index=df.index)

# 13. Combined dataset + explicit target policy
combined = pd.concat(cycles.values(), ignore_index=True)
physics_A = material_physics_components(combined)
combined = pd.concat(
    [combined.reset_index(drop=True), physics_A.reset_index(drop=True)],
    axis=1
)

if TARGET_POLICY == "exclude":
    model_df = combined[combined["target_loss_W"] >= 0].copy()
elif TARGET_POLICY == "keep":
    model_df = combined.copy()
else:
    raise ValueError("TARGET_POLICY must be 'exclude' or 'keep'")

print(f"Rows before target policy: {len(combined)}")
print(f"Rows used for modelling: {len(model_df)}")
print(f"Excluded: {len(combined)-len(model_df)}")

"""## Target diagnostics and revised motoring target
The following cells document why the original standstill-offset target is not used for the redesigned primary study. They preserve the diagnostics and then create the final motoring-only raw measured-loss target used by subsequent experiments.
"""

# 13A. Diagnose negative adjusted-loss samples

diag_neg = combined.copy()

print("Overall:")
print(f"Total points: {len(diag_neg)}")
print(f"Raw negative loss: {(diag_neg['measured_loss_W'] < 0).sum()} "
      f"({100*(diag_neg['measured_loss_W'] < 0).mean():.2f}%)")
print(f"Negative after offset correction: {(diag_neg['target_loss_W'] < 0).sum()} "
      f"({100*(diag_neg['target_loss_W'] < 0).mean():.2f}%)")

print("\nOperating conditions of negative adjusted-loss points:")
neg = diag_neg[diag_neg["target_loss_W"] < 0]

display(
    neg[[
        "speed_rpm",
        "torque_nm",
        "measured_loss_W",
        "standby_offset_W",
        "target_loss_W"
    ]].describe()
)

summary = pd.DataFrame({
    "Negative adjusted loss": [
        neg["speed_rpm"].abs().median(),
        neg["torque_nm"].abs().median(),
        neg["mechanical_power_from_Tw_W"].abs().median(),
        neg["measured_loss_W"].median()
    ],
    "Non-negative adjusted loss": [
        diag_neg.loc[diag_neg["target_loss_W"] >= 0, "speed_rpm"].abs().median(),
        diag_neg.loc[diag_neg["target_loss_W"] >= 0, "torque_nm"].abs().median(),
        diag_neg.loc[diag_neg["target_loss_W"] >= 0,
                     "mechanical_power_from_Tw_W"].abs().median(),
        diag_neg.loc[diag_neg["target_loss_W"] >= 0, "measured_loss_W"].median()
    ]
}, index=[
    "Median |speed| [rpm]",
    "Median |torque| [Nm]",
    "Median |mechanical power| [W]",
    "Median raw measured loss [W]"
])

display(summary)

plt.figure(figsize=(8,5))
plt.scatter(
    diag_neg.loc[diag_neg["target_loss_W"] >= 0, "speed_rpm"],
    diag_neg.loc[diag_neg["target_loss_W"] >= 0, "torque_nm"],
    s=5, alpha=0.15, label="Non-negative adjusted loss"
)
plt.scatter(
    neg["speed_rpm"],
    neg["torque_nm"],
    s=8, alpha=0.5, label="Negative adjusted loss"
)
plt.xlabel("Speed [rpm]")
plt.ylabel("Torque [Nm]")
plt.title("Location of negative adjusted-loss samples")
plt.legend()
plt.grid(alpha=0.3)
plt.show()

# 13B. Diagnose genuinely negative RAW measured-loss samples

raw_neg = combined[combined["measured_loss_W"] < 0].copy()

print(f"Raw negative points: {len(raw_neg)} / {len(combined)} "
      f"({100*len(raw_neg)/len(combined):.2f}%)")

print("\nBy drive cycle:")
display(
    combined.groupby("group").apply(
        lambda g: pd.Series({
            "n_total": len(g),
            "n_raw_negative": (g["measured_loss_W"] < 0).sum(),
            "raw_negative_pct":
                100*(g["measured_loss_W"] < 0).mean()
        })
    )
)

print("\nOperating conditions of raw-negative points:")
display(
    raw_neg[[
        "speed_rpm",
        "torque_nm",
        "mechanical_power_from_Tw_W",
        "input_power_W",
        "output_power_aligned_W",
        "measured_loss_W"
    ]].describe()
)

plt.figure(figsize=(8,5))
plt.scatter(
    combined.loc[combined["measured_loss_W"] >= 0, "speed_rpm"],
    combined.loc[combined["measured_loss_W"] >= 0, "torque_nm"],
    s=5, alpha=0.10,
    label="Non-negative raw loss"
)
plt.scatter(
    raw_neg["speed_rpm"],
    raw_neg["torque_nm"],
    s=10, alpha=0.6,
    label="Negative raw loss"
)
plt.xlabel("Speed [rpm]")
plt.ylabel("Torque [Nm]")
plt.title("Location of genuinely negative raw-loss samples")
plt.legend()
plt.grid(alpha=0.3)
plt.show()

# 13C. Final target policy for redesigned primary study: motoring operation

# Use the raw measured input-output loss as the target.
# Restrict the primary study to motoring / non-negative torque operation.
# The earlier offset-corrected target is retained above only as a diagnostic.
combined["target_loss_W"] = combined["measured_loss_W"]

model_df = combined[
    (combined["torque_nm"] >= 0) &
    (combined["measured_loss_W"] >= 0)
].copy()

print(f"Total measured points: {len(combined)}")
print(f"Motoring points used for modelling: {len(model_df)}")
print(f"Fraction retained: {100*len(model_df)/len(combined):.2f}%")

print("\nTarget statistics:")
display(model_df["target_loss_W"].describe())

"""## Reduced-order model B

Fit a compact interpretable model:

\[
P =
a_0+a_1|\omega|+a_2\omega^2+a_3T^2+a_4|\omega T|
\]

This serves as a strong engineering baseline and tells us whether a neural network is truly necessary.
"""

# 14. Reduced-order model and material-model parasitic correction
def reduced_order_matrix(df):
    omega = df["omega_rad_s"].values.astype(float)
    torque = df["torque_nm"].values.astype(float)
    return np.column_stack([
        np.ones(len(df)),
        np.abs(omega),
        omega**2,
        torque**2,
        np.abs(omega*torque)
    ])

def fit_reduced_order(train_df):
    model = Ridge(alpha=1e-8, fit_intercept=False)
    model.fit(reduced_order_matrix(train_df), train_df["target_loss_W"].values)
    return model

def predict_reduced_order(model, df):
    return model.predict(reduced_order_matrix(df))

def fit_parasitic_correction(train_df):
    omega = train_df["omega_rad_s"].values.astype(float)
    A = np.column_stack([np.abs(omega), omega**2])
    residual = (
        train_df["target_loss_W"].values -
        train_df["P_physics_A_base_W"].values
    )
    return np.linalg.lstsq(A, residual, rcond=None)[0]

def predict_material_with_parasitic(df, coeffs):
    omega = df["omega_rad_s"].values.astype(float)
    correction = coeffs[0]*np.abs(omega) + coeffs[1]*omega**2
    return df["P_physics_A_base_W"].values + correction

# 15. ML features and model factories
def make_feature_frame(df, mode="basic"):
    out = pd.DataFrame(index=df.index)
    out["speed_rpm"] = df["speed_rpm"].astype(float)
    out["torque_nm"] = df["torque_nm"].astype(float)

    if mode in ("engineered", "with_physics"):
        out["abs_speed"] = np.abs(df["speed_rpm"].astype(float))
        out["speed_sq"] = df["speed_rpm"].astype(float)**2
        out["torque_sq"] = df["torque_nm"].astype(float)**2
        out["abs_speed_torque"] = np.abs(
            df["speed_rpm"].astype(float) * df["torque_nm"].astype(float)
        )

    if mode == "with_physics":
        out["physics_A_base_W"] = df["P_physics_A_base_W"].astype(float)

    return out

def make_polynomial_model():
    return Pipeline([
        ("poly", PolynomialFeatures(degree=2, include_bias=False)),
        ("scale", StandardScaler()),
        ("ridge", Ridge(alpha=1e-3))
    ])

def make_gbt():
    return HistGradientBoostingRegressor(
        max_iter=300,
        learning_rate=0.05,
        max_leaf_nodes=31,
        l2_regularization=1e-3,
        random_state=SEED
    )

def make_mlp(seed=SEED):
    return Pipeline([
        ("scale", StandardScaler()),
        ("mlp", MLPRegressor(
            hidden_layer_sizes=(32,32),
            activation="relu",
            solver="adam",
            max_iter=2000,
            early_stopping=True,
            validation_fraction=0.15,
            random_state=seed
        ))
    ])

# 16. Physics-guided neural network
class TorchMLP(nn.Module):
    def __init__(self, n_features):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n_features, 32),
            nn.ReLU(),
            nn.Linear(32, 32),
            nn.ReLU(),
            nn.Linear(32, 1)
        )

    def forward(self, x):
        return self.net(x).squeeze(-1)

def train_physics_guided_nn(X_train, y_train, physics_train, lam, epochs=250, lr=1e-3, seed=SEED):
    torch.manual_seed(seed)

    scaler = StandardScaler()
    Xs = scaler.fit_transform(X_train)

    X_t = torch.tensor(Xs, dtype=torch.float32)
    y_t = torch.tensor(np.asarray(y_train), dtype=torch.float32)
    p_t = torch.tensor(np.asarray(physics_train), dtype=torch.float32)

    model = TorchMLP(X_t.shape[1])
    optimizer = torch.optim.Adam(model.parameters(), lr=lr)

    for epoch in range(epochs):
        optimizer.zero_grad()
        pred = model(X_t)

        data_loss = nn.functional.mse_loss(pred, y_t)
        physics_loss = nn.functional.mse_loss(pred, p_t)
        loss = data_loss + lam*physics_loss

        loss.backward()
        optimizer.step()

    return model, scaler

def predict_torch(model, scaler, X):
    Xs = scaler.transform(X)
    Xt = torch.tensor(Xs, dtype=torch.float32)
    model.eval()
    with torch.no_grad():
        return model(Xt).cpu().numpy()

"""# Experiment 1 — Random vs blocked in-distribution testing

The random split is retained for comparability with the original notebook.

The blocked split is harder because contiguous portions of each cycle are held out rather than randomly intermixing neighboring samples.
"""

# 17. Split helpers
def random_stratified_split(df):
    train, temp = train_test_split(
        df,
        test_size=0.30,
        random_state=SEED,
        stratify=df["group"]
    )
    val, test = train_test_split(
        temp,
        test_size=0.50,
        random_state=SEED,
        stratify=temp["group"]
    )
    return train.copy(), val.copy(), test.copy()

def blocked_within_group_split(df, train_frac=0.70, val_frac=0.15):
    train_parts, val_parts, test_parts = [], [], []

    for _, g in df.groupby("group"):
        g = g.sort_values("time_s")
        n = len(g)
        i1 = int(train_frac*n)
        i2 = int((train_frac+val_frac)*n)

        train_parts.append(g.iloc[:i1])
        val_parts.append(g.iloc[i1:i2])
        test_parts.append(g.iloc[i2:])

    return (
        pd.concat(train_parts).copy(),
        pd.concat(val_parts).copy(),
        pd.concat(test_parts).copy()
    )

train_r, val_r, test_r = random_stratified_split(model_df)
train_b, val_b, test_b = blocked_within_group_split(model_df)

print("Random split:", len(train_r), len(val_r), len(test_r))
print("Blocked split:", len(train_b), len(val_b), len(test_b))

# 18. Unified model suite
def run_model_suite(train_df, val_df, test_df, feature_mode="basic"):
    results = []
    predictions = {}

    y_train = train_df["target_loss_W"].values
    y_val = val_df["target_loss_W"].values
    y_test = test_df["target_loss_W"].values

    X_train = make_feature_frame(train_df, feature_mode).values
    X_val = make_feature_frame(val_df, feature_mode).values
    X_test = make_feature_frame(test_df, feature_mode).values

    # Material physics only: no drive-cycle fitting / no training dependence
    predictions["Material_physics_only"] = test_df["P_physics_A_base_W"].values.copy()

    # Physics A: material physics + speed-dependent nuisance correction
    # Calibrate nuisance correction on TRAIN only.
    parasitic = fit_parasitic_correction(train_df)
    p_train = predict_material_with_parasitic(train_df, parasitic)
    p_val = predict_material_with_parasitic(val_df, parasitic)
    p_test = predict_material_with_parasitic(test_df, parasitic)
    predictions["Physics_A"] = p_test

    # Reduced-order
    rom = fit_reduced_order(train_df)
    predictions["Reduced_order"] = predict_reduced_order(rom, test_df)

    # Polynomial
    poly = make_polynomial_model()
    poly.fit(X_train, y_train)
    predictions["Polynomial"] = poly.predict(X_test)

    # Gradient boosting
    gbt = make_gbt()
    gbt.fit(X_train, y_train)
    predictions["Gradient_boosting"] = gbt.predict(X_test)

    # Pure MLP
    mlp = make_mlp()
    mlp.fit(X_train, y_train)
    predictions["Data_MLP"] = mlp.predict(X_test)

    # Residual MLP
    residual_model = make_mlp()
    residual_model.fit(X_train, y_train - p_train)
    predictions["Residual_MLP"] = p_test + residual_model.predict(X_test)

    # Physics-guided NN: select lambda using validation only
    lambda_rows = []
    best_lambda = None
    best_val_mae = np.inf
    best_bundle = None

    for lam in PHYSICS_LAMBDAS:
        model_pg, scaler_pg = train_physics_guided_nn(
            X_train, y_train, p_train, lam=lam
        )
        pred_val = predict_torch(model_pg, scaler_pg, X_val)
        val_mae = mean_absolute_error(y_val, pred_val)

        lambda_rows.append({"lambda": lam, "val_MAE_W": val_mae})

        if val_mae < best_val_mae:
            best_val_mae = val_mae
            best_lambda = lam
            best_bundle = (model_pg, scaler_pg)

    predictions["Physics_guided_NN"] = predict_torch(
        best_bundle[0], best_bundle[1], X_test
    )

    for name, pred in predictions.items():
        row = metrics_dict(y_test, pred)
        row["model"] = name
        results.append(row)

    return {
        "metrics": pd.DataFrame(results).set_index("model").sort_values("MAE_W"),
        "predictions": predictions,
        "best_lambda": best_lambda,
        "lambda_table": pd.DataFrame(lambda_rows),
        "parasitic_coeffs": parasitic
    }

# 19. Run in-distribution experiments
random_results = run_model_suite(train_r, val_r, test_r)
blocked_results = run_model_suite(train_b, val_b, test_b)

print("RANDOM SPLIT")
display(random_results["metrics"])
print("Best lambda:", random_results["best_lambda"])

print("\nBLOCKED SPLIT")
display(blocked_results["metrics"])
print("Best lambda:", blocked_results["best_lambda"])

# 20. Lambda sweep
lambda_table = random_results["lambda_table"]

plt.figure(figsize=(7,4.5))
plt.plot(lambda_table["lambda"], lambda_table["val_MAE_W"], "o-")
plt.xscale("symlog", linthresh=0.01)
plt.xlabel("Physics weight lambda")
plt.ylabel("Validation MAE [W]")
plt.title("Physics-guided NN lambda sweep")
plt.grid(alpha=0.3)
plt.show()

display(lambda_table)

"""# Experiment 2 — Leave-one-cycle-out generalization

Every vehicle/cycle group is held out once.

This prevents the conclusion from depending only on Artemis.
"""

# 21. Leave-one-group-out
logo_rows = []
groups = sorted(model_df["group"].unique())

for held_out in groups:
    test_df = model_df[model_df["group"] == held_out].copy()
    remaining = model_df[model_df["group"] != held_out].copy()

    remaining_groups = sorted(remaining["group"].unique())

    if len(remaining_groups) >= 2:
        val_group = remaining_groups[-1]
        val_df = remaining[remaining["group"] == val_group].copy()
        train_df = remaining[remaining["group"] != val_group].copy()
    else:
        train_df, val_df = train_test_split(
            remaining, test_size=0.2, random_state=SEED
        )

    result = run_model_suite(train_df, val_df, test_df)

    for model_name, row in result["metrics"].iterrows():
        logo_rows.append({
            "held_out_group": held_out,
            "model": model_name,
            "best_lambda": (
                result["best_lambda"]
                if model_name == "Physics_guided_NN" else np.nan
            ),
            **row.to_dict()
        })

logo_df = pd.DataFrame(logo_rows)

print("Mean leave-one-cycle-out performance:")
display(
    logo_df.groupby("model")[["MAE_W","RMSE_W","R2","MedianRelErr_pct","MeanRelErr_pct"]]
    .agg(["mean","std"])
)

print("\nPer held-out cycle:")
display(logo_df.sort_values(["held_out_group","MAE_W"]))

"""# Experiment 3 — Explicit operating-region extrapolation

An unseen drive cycle may still lie inside the same operating map.

We therefore hold out:

- top 25% of absolute speed,
- top 25% of absolute torque.

This more directly tests whether physics helps extrapolation.
"""

# 22. Extrapolation splits
def make_extrapolation_split(df, kind="speed", train_fraction=0.75):
    if kind == "speed":
        quantity = np.abs(df["speed_rpm"].values)
    elif kind == "torque":
        quantity = np.abs(df["torque_nm"].values)
    else:
        raise ValueError("kind must be 'speed' or 'torque'")

    threshold = np.quantile(quantity, train_fraction)

    train_pool = df[quantity < threshold].copy()
    test = df[quantity >= threshold].copy()

    train, val = train_test_split(
        train_pool,
        test_size=0.18,
        random_state=SEED
    )
    return train.copy(), val.copy(), test.copy(), threshold

extrap_results = {}

for kind in ["speed", "torque"]:
    tr, va, te, threshold = make_extrapolation_split(model_df, kind)
    result = run_model_suite(tr, va, te)
    extrap_results[kind] = result

    print(f"\n{kind.upper()} extrapolation threshold = {threshold:.4f}")
    display(result["metrics"])

"""## 2-D operating-map support

Check nearest-neighbor distance in standardized speed-torque space.

This is more informative than checking speed and torque ranges separately.
"""

# 23. 2-D support distance for held-out cycles
def support_distance(train_df, test_df):
    scaler = StandardScaler()
    Xtr = scaler.fit_transform(make_feature_frame(train_df, "basic"))
    Xte = scaler.transform(make_feature_frame(test_df, "basic"))

    nn_model = NearestNeighbors(n_neighbors=1).fit(Xtr)
    dist, _ = nn_model.kneighbors(Xte)
    return dist[:,0]

support_rows = []

for held_out in groups:
    tr = model_df[model_df["group"] != held_out]
    te = model_df[model_df["group"] == held_out]
    d = support_distance(tr, te)

    support_rows.append({
        "held_out_group": held_out,
        "median_nn_distance": np.median(d),
        "p95_nn_distance": np.quantile(d, 0.95),
        "max_nn_distance": np.max(d)
    })

support_df = pd.DataFrame(support_rows)
display(support_df)

"""# Experiment 4 — Low-data efficiency with operating-map-aware sampling

Instead of selecting random neighboring time samples, spread samples across occupied speed-torque bins.
"""

# 24. Operating-map-aware sampler
def add_operating_bins(df):
    out = df.copy()

    out["_speed_bin"] = pd.qcut(
        out["speed_rpm"].rank(method="first"),
        q=N_SPEED_BINS,
        labels=False,
        duplicates="drop"
    )

    out["_torque_bin"] = pd.qcut(
        out["torque_nm"].rank(method="first"),
        q=N_TORQUE_BINS,
        labels=False,
        duplicates="drop"
    )

    out["_op_bin"] = (
        out["_speed_bin"].astype(str) + "_" +
        out["_torque_bin"].astype(str)
    )

    return out

def operating_map_sample(df, n, seed):
    rng = np.random.RandomState(seed)
    binned = add_operating_bins(df)

    bins = [g for _, g in binned.groupby("_op_bin")]
    rng.shuffle(bins)

    selected = []

    # First pass: one sample per occupied bin.
    for g in bins:
        if len(selected) >= n:
            break
        selected.append(
            g.sample(1, random_state=rng.randint(0, 2**31-1)).index[0]
        )

    # Add more if n is larger than number of occupied bins.
    remaining = binned.index.difference(selected)
    if len(selected) < n:
        extra_n = min(n-len(selected), len(remaining))
        extra = rng.choice(remaining.values, size=extra_n, replace=False)
        selected.extend(extra.tolist())

    return df.loc[selected].copy()

"""### Low-data experiment notes
* `Gradient_boosting`, `Data_MLP`, `Residual_MLP`, the reduced-order model, and `Physics_A` are retrained for every training-set size.
* `Material_physics_only` uses only the material-derived copper and iron model and therefore does not depend on the number of drive-cycle training points.
* `Physics_A` is not training-independent because its speed-dependent parasitic correction is fitted on the current training subset.
* The physics-guided model selects `lambda` using the fixed validation set only. The held-out test set is not used for hyperparameter selection.
* The notebook records the selected `lambda` for every training size and repeat so this can be audited directly.
"""

# 25. Low-data sweep with TOTAL labeled measurement budget
# --------------------------------------------------------
# The x-axis now means TOTAL characterization points available.
# For each budget:
#   80% -> training
#   20% -> validation / lambda selection
# The fixed test set remains completely untouched.

dev_pool = pd.concat([train_r, val_r], ignore_index=True).copy()
test_fixed = test_r.copy()

VAL_FRACTION = 0.20

low_rows_budget = []

for n_budget in LOW_DATA_SIZES + [len(dev_pool)]:

    n_budget_use = min(n_budget, len(dev_pool))

    for repeat in range(LOW_DATA_REPEATS):

        # ----------------------------------------------------
        # 1. Select the TOTAL labeled characterization budget
        # ----------------------------------------------------
        if n_budget_use == len(dev_pool):
            budget_df = dev_pool.copy()
        else:
            budget_df = operating_map_sample(
                dev_pool,
                n_budget_use,
                seed=20000 + 100*n_budget_use + repeat
            )

        # ----------------------------------------------------
        # 2. Split that budget into train and validation
        # ----------------------------------------------------
        n_val = max(1, int(round(VAL_FRACTION * len(budget_df))))
        n_train = len(budget_df) - n_val

        # Keep the validation points distributed over the
        # operating map rather than taking a purely random slice.
        val_sub = operating_map_sample(
            budget_df,
            n_val,
            seed=30000 + 100*n_budget_use + repeat
        )

        train_sub = budget_df.drop(index=val_sub.index).copy()

        # Safety check
        assert len(train_sub) + len(val_sub) == len(budget_df)

        # ----------------------------------------------------
        # 3. Run all models
        #
        # Lambda is selected ONLY on val_sub.
        # test_fixed is untouched until final evaluation.
        # ----------------------------------------------------
        result = run_model_suite(
            train_sub,
            val_sub,
            test_fixed
        )

        for model_name, row in result["metrics"].iterrows():

            low_rows_budget.append({
                "n_budget": len(budget_df),
                "n_train": len(train_sub),
                "n_val": len(val_sub),
                "repeat": repeat,
                "model": model_name,

                "best_lambda": (
                    result["best_lambda"]
                    if model_name == "Physics_guided_NN"
                    else np.nan
                ),

                **row.to_dict()
            })


low_data_budget_df = pd.DataFrame(low_rows_budget)


# ============================================================
# MAE SUMMARY
# ============================================================

low_budget_mae_summary = (
    low_data_budget_df
    .groupby(["n_budget", "model"])["MAE_W"]
    .agg(["mean", "std"])
    .reset_index()
)

print("Low-data MAE summary using TOTAL characterization budget:")
display(low_budget_mae_summary)


# ============================================================
# RELATIVE ERROR SUMMARY
# ============================================================

low_budget_rel_summary = (
    low_data_budget_df
    .groupby(["n_budget", "model"])[
        ["MedianRelErr_pct", "MeanRelErr_pct"]
    ]
    .agg(["mean", "std"])
)

print("\nLow-data relative-error summary:")
display(low_budget_rel_summary)


# ============================================================
# LAMBDA HISTORY
# ============================================================

lambda_budget_history = (
    low_data_budget_df[
        low_data_budget_df["model"] == "Physics_guided_NN"
    ][
        [
            "n_budget",
            "n_train",
            "n_val",
            "repeat",
            "best_lambda",
            "MAE_W",
            "MedianRelErr_pct",
            "MeanRelErr_pct"
        ]
    ]
    .sort_values(["n_budget", "repeat"])
    .reset_index(drop=True)
)

print("\nSelected lambda for every budget/repeat:")
display(lambda_budget_history)


# ============================================================
# LAMBDA SELECTION COUNTS
# ============================================================

lambda_budget_summary = (
    lambda_budget_history
    .groupby(["n_budget", "best_lambda"])
    .size()
    .rename("selection_count")
    .reset_index()
)

print("\nLambda selection counts by TOTAL characterization budget:")
display(lambda_budget_summary)

# 26. Plot low-data study using TOTAL characterization budget
# ----------------------------------------------------------

models_to_plot = [
    "Material_physics_only",
    "Physics_A",
    "Reduced_order",
    "Gradient_boosting",
    "Data_MLP",
    "Residual_MLP",
    "Physics_guided_NN"
]


# ============================================================
# 1. PRIMARY FIGURE: MAE
# ============================================================

plt.figure(figsize=(10,6))

for model_name in models_to_plot:

    d = low_budget_mae_summary[
        low_budget_mae_summary["model"] == model_name
    ]

    if len(d) == 0:
        continue

    plt.errorbar(
        d["n_budget"],
        d["mean"],
        yerr=d["std"],
        marker="o",
        label=model_name
    )

plt.xscale("log")
plt.xlabel("Total labeled characterization operating points")
plt.ylabel("Test MAE [W]")
plt.title("Data efficiency with fixed characterization budget")
plt.grid(alpha=0.3, which="both")
plt.legend()
plt.show()


# ============================================================
# 2. MEAN RELATIVE ERROR
# ============================================================

mean_rel_budget_plot = (
    low_data_budget_df
    .groupby(["n_budget", "model"])["MeanRelErr_pct"]
    .agg(["mean", "std"])
    .reset_index()
)

plt.figure(figsize=(10,6))

for model_name in models_to_plot:

    d = mean_rel_budget_plot[
        mean_rel_budget_plot["model"] == model_name
    ]

    if len(d) == 0:
        continue

    plt.errorbar(
        d["n_budget"],
        d["mean"],
        yerr=d["std"],
        marker="o",
        label=model_name
    )

plt.xscale("log")
plt.xlabel("Total labeled characterization operating points")
plt.ylabel("Mean relative test error [%]")
plt.title("Data efficiency: mean relative error")
plt.grid(alpha=0.3, which="both")
plt.legend()
plt.show()


# ============================================================
# 3. MEDIAN RELATIVE ERROR
# ============================================================

median_rel_budget_plot = (
    low_data_budget_df
    .groupby(["n_budget", "model"])["MedianRelErr_pct"]
    .agg(["mean", "std"])
    .reset_index()
)

plt.figure(figsize=(10,6))

for model_name in models_to_plot:

    d = median_rel_budget_plot[
        median_rel_budget_plot["model"] == model_name
    ]

    if len(d) == 0:
        continue

    plt.errorbar(
        d["n_budget"],
        d["mean"],
        yerr=d["std"],
        marker="o",
        label=model_name
    )

plt.xscale("log")
plt.xlabel("Total labeled characterization operating points")
plt.ylabel("Median relative test error [%]")
plt.title("Data efficiency: median relative error")
plt.grid(alpha=0.3, which="both")
plt.legend()
plt.show()

"""# Experiment 5 — Residual structure

Before deciding a neural network is required, inspect whether the physics residual has a simple relationship with speed, torque, or mechanical power.
"""

# 27. Residual diagnostics
parasitic = fit_parasitic_correction(train_r)
pred_phys_train = predict_material_with_parasitic(train_r, parasitic)

diag = train_r.copy()
diag["physics_residual_W"] = (
    diag["target_loss_W"].values - pred_phys_train
)
diag["abs_speed_rpm"] = np.abs(diag["speed_rpm"])
diag["torque_sq"] = diag["torque_nm"]**2
diag["abs_mech_power_W"] = np.abs(diag["mechanical_power_from_Tw_W"])

for xcol in [
    "abs_speed_rpm",
    "torque_nm",
    "torque_sq",
    "abs_mech_power_W"
]:
    plt.figure(figsize=(7,4))
    plt.scatter(
        diag[xcol],
        diag["physics_residual_W"],
        s=6,
        alpha=0.2
    )
    plt.axhline(0, lw=1)
    plt.xlabel(xcol)
    plt.ylabel("Measured - physics [W]")
    plt.title(f"Physics residual vs {xcol}")
    plt.grid(alpha=0.3)
    plt.show()

"""# Experiment 6 — Winding-temperature sensitivity

If winding temperature is unavailable, do not assume stator resistance is exact.

Sweep plausible winding temperature and see how much the physics-model error changes.
"""

# 28. Copper-loss temperature sensitivity
TEMP_SWEEP_C = [20, 40, 60, 80, 100, 120]

temp_rows = []
parasitic = random_results["parasitic_coeffs"]

for temp_C in TEMP_SWEEP_C:
    comp = material_physics_components(
        test_r,
        Rs=Rs_ref,
        winding_temp_C=np.full(len(test_r), temp_C)
    )

    omega = test_r["omega_rad_s"].values
    extra = parasitic[0]*np.abs(omega) + parasitic[1]*omega**2
    pred = comp["P_physics_A_base_W"].values + extra

    row = metrics_dict(test_r["target_loss_W"].values, pred)
    row["assumed_winding_temp_C"] = temp_C
    temp_rows.append(row)

temp_df = pd.DataFrame(temp_rows)
display(temp_df)

plt.figure(figsize=(7,4))
plt.plot(temp_df["assumed_winding_temp_C"], temp_df["MAE_W"], "o-")
plt.xlabel("Assumed winding temperature [°C]")
plt.ylabel("Physics-model MAE [W]")
plt.title("Sensitivity to winding resistance temperature")
plt.grid(alpha=0.3)
plt.show()

"""# Experiment 7 — Cycle-integrated loss energy

For a drive-cycle application, total loss energy can matter as much as instantaneous error.
"""

# 29. Cycle-energy evaluation for leave-one-cycle-out
energy_rows = []

for held_out in groups:
    test_df = model_df[model_df["group"] == held_out].copy()
    remaining = model_df[model_df["group"] != held_out].copy()
    remaining_groups = sorted(remaining["group"].unique())

    if len(remaining_groups) >= 2:
        val_group = remaining_groups[-1]
        val_df = remaining[remaining["group"] == val_group].copy()
        train_df = remaining[remaining["group"] != val_group].copy()
    else:
        train_df, val_df = train_test_split(
            remaining, test_size=0.2, random_state=SEED
        )

    result = run_model_suite(train_df, val_df, test_df)

    order = np.argsort(test_df["time_s"].values)
    t = test_df["time_s"].values[order]
    y = test_df["target_loss_W"].values[order]

    for model_name, pred in result["predictions"].items():
        pred_sorted = np.asarray(pred)[order]
        m = metrics_dict(y, pred_sorted, time_s=t)

        energy_rows.append({
            "held_out_group": held_out,
            "model": model_name,
            "CycleEnergyErr_pct": m["CycleEnergyErr_pct"],
            "TrueEnergy_Wh": m["TrueEnergy_Wh"],
            "PredEnergy_Wh": m["PredEnergy_Wh"]
        })

energy_df = pd.DataFrame(energy_rows)

display(
    energy_df.groupby("model")["CycleEnergyErr_pct"]
    .agg(["mean","std","median"])
    .sort_values("mean")
)

